-- Create Warehouses
CREATE OR REPLACE WAREHOUSE MARKETING_WH WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE OR REPLACE WAREHOUSE FINANCE_WH   WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE OR REPLACE WAREHOUSE ETL_WH       WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- Create Roles
CREATE OR REPLACE ROLE MARKETING_ANALYST;
CREATE OR REPLACE ROLE FINANCE_USER;
CREATE OR REPLACE ROLE ETL_DEVELOPER;


-- Grant Warehouse access to Roles
GRANT USAGE ON WAREHOUSE MARKETING_WH TO ROLE MARKETING_ANALYST;
GRANT USAGE ON WAREHOUSE FINANCE_WH   TO ROLE FINANCE_USER;
GRANT USAGE ON WAREHOUSE ETL_WH       TO ROLE ETL_DEVELOPER;

-- part 3
-- Create Users setup
CREATE OR REPLACE USER MKT_USER1 PASSWORD='User123' DEFAULT_ROLE=MARKETING_ANALYST DEFAULT_WAREHOUSE=MARKETING_WH MUST_CHANGE_PASSWORD=FALSE;
CREATE OR REPLACE USER FIN_USER1 PASSWORD='User123' DEFAULT_ROLE=FINANCE_USER     DEFAULT_WAREHOUSE=FINANCE_WH   MUST_CHANGE_PASSWORD=FALSE;
CREATE OR REPLACE USER ETL_USER1 PASSWORD='User123' DEFAULT_ROLE=ETL_DEVELOPER    DEFAULT_WAREHOUSE=ETL_WH       MUST_CHANGE_PASSWORD=FALSE;

-- Assign Roles to Users
GRANT ROLE MARKETING_ANALYST TO USER MKT_USER1;
GRANT ROLE FINANCE_USER     TO USER FIN_USER1;
GRANT ROLE ETL_DEVELOPER    TO USER ETL_USER1;


-- part 4,5 Database, Table, and Permissions
-- Create Database
CREATE OR REPLACE DATABASE RETAIL_MARKETING_DB;

-- Create Table from Sample Data
CREATE OR REPLACE TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES AS
SELECT 
    s.SS_SOLD_DATE_SK,
    d.D_DATE AS SALE_DATE,
    s.SS_ITEM_SK,
    i.I_ITEM_ID,     
    c.C_CUSTOMER_SK,
    c.C_FIRST_NAME,
    c.C_LAST_NAME,
    s.SS_SALES_PRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES s
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM d ON s.SS_SOLD_DATE_SK = d.D_DATE_SK
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER c ON s.SS_CUSTOMER_SK = c.C_CUSTOMER_SK
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM i ON s.SS_ITEM_SK = i.I_ITEM_SK
WHERE d.D_YEAR = 2002  
LIMIT 1000000;         

-- Grant usage on Database to each role individually
GRANT USAGE ON DATABASE RETAIL_MARKETING_DB TO ROLE MARKETING_ANALYST;
GRANT USAGE ON DATABASE RETAIL_MARKETING_DB TO ROLE FINANCE_USER;
GRANT USAGE ON DATABASE RETAIL_MARKETING_DB TO ROLE ETL_DEVELOPER;

-- Grant usage on Schema to each role individually
GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC TO ROLE MARKETING_ANALYST;
GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC TO ROLE FINANCE_USER;
GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC TO ROLE ETL_DEVELOPER;


-- step 6 performance testing
-- Set warehouse to its smallest size
ALTER WAREHOUSE MARKETING_WH SET WAREHOUSE_SIZE = 'XSMALL';

-- Run a sales analysis query 
SELECT C_FIRST_NAME, C_LAST_NAME, I_ITEM_ID, SUM(SS_SALES_PRICE) AS TOTAL_SPENT
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES 
GROUP BY 1, 2, 3 
ORDER BY TOTAL_SPENT DESC;

--  Scale up to SMALL
ALTER WAREHOUSE MARKETING_WH SET WAREHOUSE_SIZE = 'SMALL';

-- Run the exact same query again to  compare the speed
SELECT C_FIRST_NAME, C_LAST_NAME, I_ITEM_ID, SUM(SS_SALES_PRICE) AS TOTAL_SPENT
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES 
GROUP BY 1, 2, 3 
ORDER BY TOTAL_SPENT DESC;

--  Scale back down to save credits
ALTER WAREHOUSE MARKETING_WH SET WAREHOUSE_SIZE = 'XSMALL';


-- step 7 cache testing
-- Run this query for the first time (Snowflake calculates from data)
SELECT AVG(SS_SALES_PRICE), MAX(SS_SALES_PRICE) 
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES;

-- Run it again immediately (Snowflake pulls from cache - should take 0.0s)
SELECT AVG(SS_SALES_PRICE), MAX(SS_SALES_PRICE) 
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES;



-- SELECT DISTINCT SALE_DATE 
-- FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES 
-- LIMIT 10;

-- step 8
--  Run date-filter BEFORE clustering (Use July)
SELECT * FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES 
WHERE SALE_DATE BETWEEN '2002-07-01' AND '2002-07-31';

--  Add/Refresh the Cluster Key
ALTER TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES CLUSTER BY (SALE_DATE);

SELECT * FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES 
WHERE SALE_DATE BETWEEN '2002-07-01' AND '2002-07-31';