--create db
CREATE OR REPLACE TRANSIENT DATABASE STREAMS_DB;
USE DATABASE STREAMS_DB;

--Create Raw Sales Staging Table
CREATE OR REPLACE TABLE SALES_RAW_STAGING (
    ID INT,
    PRODUCT STRING,
    PRICE NUMBER(10,2),
    AMOUNT INT,
    STORE_ID INT
);

--insert data
INSERT INTO SALES_RAW_STAGING VALUES
(1,'Banana',1.99,1,1),
(2,'Lemon',0.99,1,1),
(3,'Apple',1.79,1,2),
(4,'Orange Juice',1.89,1,NULL),
(5,'Cereals',5.98,2,1);

--Create Store Table
CREATE OR REPLACE TABLE STORE_TABLE (
    STORE_ID INT,
    LOCATION STRING,
    EMPLOYEES INT
);

--Insert Store Data
INSERT INTO STORE_TABLE VALUES
(1,'Chicago',33),
(2,'London',12);

--Create Final Sales Table
CREATE OR REPLACE TABLE SALES_FINAL_TABLE (
    ID INT,
    PRODUCT STRING,
    PRICE NUMBER(10,2),
    AMOUNT INT,
    STORE_ID INT,
    LOCATION STRING,
    EMPLOYEES INT
);

--Perform Initial Full Load
INSERT INTO SALES_FINAL_TABLE
SELECT
    S.ID,
    S.PRODUCT,
    S.PRICE,
    S.AMOUNT,
    S.STORE_ID,
    ST.LOCATION,
    ST.EMPLOYEES
FROM SALES_RAW_STAGING S
LEFT JOIN STORE_TABLE ST
ON S.STORE_ID = ST.STORE_ID;

--Verify Initial Load
SELECT * FROM SALES_RAW_STAGING;

SELECT * FROM STORE_TABLE;

SELECT * FROM SALES_FINAL_TABLE;

--Create Stream Object
CREATE OR REPLACE STREAM SALES_STREAM
ON TABLE SALES_RAW_STAGING;

-- view stream info.
SHOW STREAMS;
DESCRIBE STREAM SALES_STREAM;
SELECT * FROM SALES_STREAM;

--Insert New Sales Records
INSERT INTO SALES_RAW_STAGING VALUES
(6,'Mango',1.99,1,2),
(7,'Garlic',0.99,1,1);

--Check Stream Data
SELECT
    *,
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID
FROM SALES_STREAM;

--verify source and target value
SELECT * FROM SALES_RAW_STAGING;

SELECT * FROM SALES_FINAL_TABLE;

--Consume Stream Data
INSERT INTO SALES_FINAL_TABLE
SELECT
    S.ID,
    S.PRODUCT,
    S.PRICE,
    S.AMOUNT,
    S.STORE_ID,
    ST.LOCATION,
    ST.EMPLOYEES
FROM SALES_STREAM S
LEFT JOIN STORE_TABLE ST
ON S.STORE_ID = ST.STORE_ID
WHERE METADATA$ACTION = 'INSERT';

--Verify Stream After Consumption
SELECT * FROM SALES_STREAM;

--Insert More Sales Records
INSERT INTO SALES_RAW_STAGING VALUES
(8,'Paprika',4.99,1,2),
(9,'Tomato',3.99,1,2);

--Consume Second Stream Data
INSERT INTO SALES_FINAL_TABLE
SELECT
    S.ID,
    S.PRODUCT,
    S.PRICE,
    S.AMOUNT,
    S.STORE_ID,
    ST.LOCATION,
    ST.EMPLOYEES
FROM SALES_STREAM S
LEFT JOIN STORE_TABLE ST
ON S.STORE_ID = ST.STORE_ID
WHERE METADATA$ACTION = 'INSERT';

--Verify Final Insert Output
SELECT * FROM SALES_FINAL_TABLE;

SELECT * FROM SALES_RAW_STAGING;

SELECT * FROM SALES_STREAM;

--Check Existing Data Before Update
SELECT * FROM SALES_RAW_STAGING;

SELECT * FROM SALES_STREAM;

--Perform First Update
UPDATE SALES_RAW_STAGING
SET PRODUCT = 'Potato'
WHERE PRODUCT = 'Banana';

--Check Stream After Update
SELECT
    *,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM SALES_STREAM;

--Consume Update Using MERGE
MERGE INTO SALES_FINAL_TABLE T
USING (
    SELECT *
    FROM SALES_STREAM
    WHERE METADATA$ACTION = 'INSERT'
    AND METADATA$ISUPDATE = TRUE
) S
ON T.ID = S.ID

WHEN MATCHED THEN
UPDATE SET
    T.PRODUCT = S.PRODUCT,
    T.PRICE = S.PRICE,
    T.AMOUNT = S.AMOUNT,
    T.STORE_ID = S.STORE_ID;

--Verify First Update
SELECT * FROM SALES_FINAL_TABLE;

SELECT * FROM SALES_RAW_STAGING;

SELECT * FROM SALES_STREAM;

--Perform Second Update
UPDATE SALES_RAW_STAGING
SET PRODUCT = 'Green apple'
WHERE PRODUCT = 'Apple';

--Consume Second Update Using MERGE
MERGE INTO SALES_FINAL_TABLE T
USING (
    SELECT *
    FROM SALES_STREAM
    WHERE METADATA$ACTION = 'INSERT'
    AND METADATA$ISUPDATE = TRUE
) S
ON T.ID = S.ID

WHEN MATCHED THEN
UPDATE SET
    T.PRODUCT = S.PRODUCT,
    T.PRICE = S.PRICE,
    T.AMOUNT = S.AMOUNT,
    T.STORE_ID = S.STORE_ID;

--Verify Final Output
SELECT * FROM SALES_FINAL_TABLE;

SELECT * FROM SALES_RAW_STAGING;

SELECT * FROM SALES_STREAM;